com:
  bld:
    crypto:
      jks:
        alg: RS512
        file: classpath:keystore.jks
        alias: test
        instance-jks: PKCS12
        password: changeit
      public-key:
        keys:
          test: classpath:keystore.pub
      aes:
        keys:
          test: 
            password: Test12345!
            salt: helloWorld@123
            key-length: 256
          test1:
            password: Ci@o12345%H&llo12345ch&!
        
